DEFERRED_EXEC_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = no
TAP_DANCE_ENABLE = yes

COMBO_ENABLE = yes
OLED_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no